name: Build and upload image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Install qemu-user-static
        run: sudo apt update && sudo apt install -y qemu-user-static

      - name: Run image-builder container
        run: |
          sudo podman run --privileged --rm \
          -v "${{ github.workspace }}/output:/output" \
          ghcr.io/osbuild/image-builder-cli:latest \
          --distro fedora-41 \
          --arch riscv64 \
          build minimal-raw-zst

      - name: Change ownership of output directory
        run: sudo chown -R $(whoami):$(whoami) output

      - name: Install extra packages for testing
        run: sudo apt install -y qemu-system-riscv64 python3-pexpect qemu-efi-riscv64

      - name: Run tests
        run: |
          unzstd output/fedora-41-minimal-raw-zst-riscv64/zstd/disk.raw.zst
          python3 test.py output/fedora-41-minimal-raw-zst-riscv64/zstd/disk.raw /usr/share/qemu-efi-riscv64/RISCV_VIRT_CODE.fd

      - name: Archive the log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: testlog
          path: log

      - name: Upload the disk image
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: disk.raw
          path: output/fedora-41-minimal-raw-zst-riscv64/zstd/disk.raw

      - name: Update README
        run: |
          sed -i "s|[(].*[]][(].*[)]|[($(date +'%Y-%m-%d'))](${{ steps.upload-artifact.outputs.artifact-url }})|" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update download link in README"
          git push origin main
