name: Build and upload image

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Install qemu-user-static
        run: sudo apt update && sudo apt install -y qemu-user-static

      - name: Run image-builder container
        run: |
          sudo podman run --privileged --rm \
          -v "${{ github.workspace }}/output:/output" \
          ghcr.io/ondrejbudai/image-builder-cli:fedora-minimal-riscv \
          --distro fedora-41 \
          --arch riscv64 \
          build minimal-raw-zst

      - name: Change ownership of output directory
        run: sudo chown -R $(whoami):$(whoami) output

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: fedora-41-minimal.raw.zst
          path: output/fedora-41-minimal-raw-zst-riscv64/zstd/disk.raw.zst

      - name: Update README
        run: |
          sed -i "s|\[Download the latest image (.*)\](.*)|[Download the latest image ($(date +'%Y-%m-%d'))](${{ steps.upload-artifact.outputs.artifact-url }})|" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update download link in README"
          git push origin main
